{% set name = "hydra-image-processor" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script_env:
    - CMAKE_GENERATOR=Ninja

requirements:
  build:
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
    - cuda-version 12.4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cuda-version >=12.4

test:
  imports:
    - hydra_image_processor
    - hydra_image_processor.cuda
    - hydra_image_processor.local
  commands:
    - python -c "import hydra_image_processor; print(hydra_image_processor.__version__)"

about:
  home: https://github.com/zfphil/hydra-image-processor
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: 'A high-performance image processing library with Python bindings.'
  description: |
    Hydra Image Processor (Hydra) is a collection of signal filters for image analysis 
    that can handle 1-5 dimensional data (x, y, z, channels, time), efficiently processing 
    data larger than GPU memory by optimally chunking it.
  dev_url: https://github.com/zfphil/hydra-image-processor

extra:
  recipe-maintainers:
    - ericwait
