"""
GPU accuracy tests for hydra_image_processor.

Python port of src/MATLAB/+Test/AccuracyTest.m: runs each operation on the
two-channel test volume in test_data/ and compares the result against the
ground-truth TIFFs generated by the MATLAB suite. This is the release gate
described in TESTING.md; CI cannot run it because its runners have no GPU.

Axis convention
---------------
tifffile loads a TIFF stack as (z, y, x). Hydra maps numpy axes onto its
native (x, y, z, chan, frame) order fastest-to-slowest, so volumes are
passed exactly as tifffile loads them, channels are stacked on axis 0
-> (chan, z, y, x), and vector parameters (sigmas, radii) are given in
(z, y, x) order — the reverse of the MATLAB test, which uses (x, y, z).

Tolerances
----------
Integer ground truth allows a 1 LSB difference (rounding jitter across
CUDA toolkit/GPU generations); float ground truth uses the same 1e-4
bound as the MATLAB suite.

Requires: numpy, tifffile, a CUDA device, and `git lfs pull` so
test_data/ holds real TIFF binaries rather than LFS pointers.

Usage: python test_accuracy.py
"""

import os
import sys

import numpy as np

try:
    import tifffile
except ImportError:
    print("[SKIP] tifffile is required (conda install tifffile)")
    sys.exit(0)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import hydra_image_processor as hip

TEST_DATA_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "test_data")
)

INT_TOL = 1  # max absolute difference for integer ground truth
FLOAT_TOL = 1e-4  # max absolute difference for float ground truth (same as MATLAB)

_failures = []


def load_tif(name):
    path = os.path.join(TEST_DATA_DIR, name)
    return tifffile.imread(path)


def check(op_name, actual, expected_file):
    """Compare one output channel against a ground-truth TIFF."""
    expected = load_tif(expected_file)
    actual = np.asarray(actual)

    if actual.shape != expected.shape:
        _failures.append(f"{op_name}: shape {actual.shape} != {expected.shape} ({expected_file})")
        print(f"  [FAILED] {expected_file}: shape mismatch {actual.shape} vs {expected.shape}")
        return

    diff = np.abs(actual.astype(np.float64) - expected.astype(np.float64))
    max_diff = diff.max()
    tol = INT_TOL if np.issubdtype(expected.dtype, np.integer) else FLOAT_TOL

    if max_diff <= tol:
        print(f"  [OK] {expected_file} (maxdiff={max_diff:g})")
    else:
        _failures.append(f"{op_name}: maxdiff {max_diff:g} > {tol} ({expected_file})")
        print(f"  [FAILED] {expected_file}: maxdiff={max_diff:g} > tol={tol}")


def check_channels(op_name, out4d, file_pattern):
    check(op_name, out4d[0], file_pattern.format(c=1))
    check(op_name, out4d[1], file_pattern.format(c=2))


def main():
    print("=" * 60)
    print("Hydra Python TIFF accuracy suite")
    print("=" * 60)

    if hip.device_count() <= 0:
        print("[SKIP] No CUDA devices found. Skipping accuracy tests.")
        return True

    for f in ("test_c0.tif", "test_c1.tif"):
        path = os.path.join(TEST_DATA_DIR, f)
        if not os.path.isfile(path):
            print(f"[SKIP] Missing test input {path}")
            return True
        if os.path.getsize(path) < 4096:
            print(f"[SKIP] {f} looks like a Git LFS pointer; run `git lfs pull`")
            return True

    HIP = hip.Hydra  # raw API, mirrors the MATLAB command names

    im0 = load_tif("test_c0.tif")
    im1 = load_tif("test_c1.tif")
    im = np.ascontiguousarray(np.stack([im0, im1], axis=0))  # (chan, z, y, x)
    print(f"Input: {im.shape} {im.dtype} (chan, z, y, x)\n")

    # Per-channel min-max normalization, like ImUtils.ConvertType(im, 'single', true)
    im_norm = np.stack(
        [((c - c.min()) / float(c.max() - c.min())).astype(np.float32) for c in im], axis=0
    )

    # MATLAB: sigmas [19,19,9], radius [5,5,2] in (x,y,z) -> reversed here
    sigmas = [9.0, 19.0, 19.0]
    mask = hip.make_ellipsoid_mask([5, 5, 2])  # (x, y, z) radii, shape (11,11,5)
    kernel = np.ascontiguousarray(mask.transpose(2, 1, 0)).astype(np.float32)  # (z, y, x)

    print("Gaussian")
    check_channels("Gaussian", np.asarray(HIP.Gaussian(im, sigmas)), "Gaussian_c{c}_19-19-9.tif")

    print("HighPassFilter")
    check_channels("HighPassFilter", np.asarray(HIP.HighPassFilter(im, sigmas)),
                   "HighPassFilter_c{c}_19-19-9.tif")

    print("LoG")
    out = np.asarray(HIP.LoG(im_norm, [2.0, 4.0, 4.0])).copy()
    out[out > 0.001] = 0
    out = np.abs(out)
    check_channels("LoG", out, "LoG_c{c}_4-4-2.tif")

    for op in ("Closure", "MaxFilter", "MeanFilter", "MedianFilter",
               "MinFilter", "Opener", "StdFilter", "VarFilter"):
        print(op)
        check_channels(op, np.asarray(getattr(HIP, op)(im, kernel)), op + "_c{c}_5-5-2.tif")

    print("MultiplySum")
    check_channels("MultiplySum", np.asarray(HIP.MultiplySum(im, kernel * 3.0)),
                   "MultiplySum_c{c}_15-15-6.tif")

    print("ElementWiseDifference")
    im_rev = np.ascontiguousarray(im[::-1])
    check_channels("ElementWiseDifference", np.asarray(HIP.ElementWiseDifference(im, im_rev)),
                   "ElementWiseDifference_c{c}_reverse.tif")

    # EntropyFilter has no MATLAB reference test; its ground truth was saved
    # min-max scaled to the uint16 range, and histogram-bin edges make a few
    # pixels jump a bin across toolkit versions. Soft check: >=99.99% of
    # pixels within 1 LSB after the same scaling.
    print("EntropyFilter (soft)")
    for ch, name in ((0, "EntropyFilter_c1_5-5-2.tif"), (1, "EntropyFilter_c2_5-5-2.tif")):
        expected = load_tif(name).astype(np.float64)
        out = np.asarray(HIP.EntropyFilter(im[ch], kernel)).astype(np.float64)
        scaled = np.round((out - out.min()) / (out.max() - out.min()) * 65535.0)
        frac_bad = float((np.abs(scaled - expected) > 1).mean())
        if frac_bad < 1e-4:
            print(f"  [OK] {name} (pixels off by >1 LSB: {frac_bad:.2e})")
        else:
            _failures.append(f"EntropyFilter: {frac_bad:.2e} of pixels off by >1 LSB ({name})")
            print(f"  [FAILED] {name}: {frac_bad:.2e} of pixels off by >1 LSB")

    print()
    print("=" * 60)
    if _failures:
        print(f"FAILED: {len(_failures)} comparison(s)")
        for f in _failures:
            print(f"  - {f}")
        return False
    print("Test Summary: PASSED")
    return True


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
