classdef (Abstract,Sealed) Cuda
methods (Static)
    [imageOut] = WienerFilter(imageIn,kernel,noiseVariance,device)
    [imageOut] = VarFilter(imageIn,kernel,numIterations,device)
    [imageOut] = MinFilter(imageIn,kernel,numIterations,device)
    [imageOut] = MedianFilter(imageIn,kernel,numIterations,device)
    [imageOut] = MeanFilter(imageIn,kernel,numIterations,device)
    [imageOut] = StdFilter(imageIn,kernel,numIterations,device)
    [imageOut] = LoG(imageIn,sigmas,device)
    [imageOut] = IdentityFilter(imageIn,device)
    [imageOut] = Opener(imageIn,kernel,numIterations,device)
    [minVal,maxVal] = GetMinMax(imageIn,device)
    [imageOut] = Gaussian(imageIn,sigmas,numIterations,device)
    [imageOut] = EntropyFilter(imageIn,kernel,device)
    [imageOut] = ElementWiseDifference(image1In,image2In,device)
    [imageOut] = Closure(imageIn,kernel,numIterations,device)
    [imageOut] = Sum(imageIn,device)
    [deviceStatsArray] = DeviceStats()
    [imageOut] = MultiplySum(imageIn,kernel,numIterations,device)
    [numCudaDevices,memStats] = DeviceCount()
    [imageOut] = MaxFilter(imageIn,kernel,numIterations,device)
    [cmdInfo] = Info()
    [imageOut] = HighPassFilter(imageIn,sigmas,device)
    Help(command)
end
methods (Static, Access = private)
    varargout = Mex(command, varargin)
end
end
